export const BASE_PATH = 'asianschool.bh'
export const SITE_NAME = 'The Asian School Bahrain'
export const SITE_FAVICON ='/images/asbfavicon.png'
export const SITE_DESCRIPTION ='The Asian School is a privately owned secular co-educational institution officially opened on the 11th of May 1983 with the approval of the Ministry of Education, Kingdom of Bahrain. The institution was upgraded to the Secondary level in July 1992 and Senior Secondary level in December 2016. The school is affiliated to the Central Board of Secondary Education (CBSE), New Delhi and has a strength of around 4500 students from Kindergarten to Grade 12.'
export const baseURL='/'
export const imgblurDataURL='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mPsqQcAAZ0BDTSBuAQAAAAASUVORK5CYII='
export const HOME_OG_IMAGE_URL ='/images/asbfavicon.png'
